# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('created_by', models.IntegerField(null=True)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Board')),
            ],
        ),
    ]
